---
title: "Data Hack Competition 2022: Judges Rubric"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**Topic: What topic should be on the top of California policy makers agenda and why?**

Each of the six groups will have 15 minutes to provide a presentation on an issue occurring in California. Their job is to convince the panel of judges that this problem should be given substantial attention by California policy makers. For instance, if a group decided to choose rising murder rates as their topic, their job is to convince you that this issue is a priority because of X,Y, and Z.

Below is a rubric containing elements upon groups should be judged.  


# Rubric

## Objective Components (To Be Completed During Presentation)

The following are objective components. You can think of these as check-boxes. All presentations should have these components.

### Presentation Acumen 

- Volume: Speakers are clear and speak in a volume such that they can be heard. [  /1]
- Language: Language is professional and avoids slang. [  /1]
- Engagement: Presenters engage the audience and keep the presentation lively. [  /1]
- Movement: Presenters do not stand still and frozen. [  /1]
- Group Involvement: Each group member speaks. [  /1]
- Concise Slides: Each slide has a concise/readable amount of information. [ /1] 

*Total Presentation Acumen Points: *

### Motivation

- Presenters show why this topic is important with a meaningful graph/table/statistic. [  /1]
- Presenters' topic is clear and understandable. [  /1]
- Presenters' topic outlines why policy makers need to pay particular attention to this, and what they have/have not done in the past in regards to this issue. [  /1]

*Total Motivation Points: *

### Figures/Tables

- Figures/Tables are all clearly labeled/titled. [  /1]
- Figures/Tables look professional. [  /1]
- Figures /Tables convey a clear message. [  /1]
- There is variety in the figures/tables (i.e., not just one type of plot.) [  /1]

*Total Figures/Graphs Points:  *

\newpage

### Data

- Presenters explain each of their data sources and their corresponding reliability. [  /1]
- Presenters give brief explanation of data shortcomings. This includes large missing data/missing years etc. [  /1]
- Presenters explain their data cleaning process concisely, but clearly. They explain any necessary merges/scraping that needed to be done. [  /1]

*Total Data Points: *

## Presentation Time


| Presentation Time (Min:Sec)      |  Score   |
|----------------------------------|----------|
|  < 15:01                         |   5  |
|  Between 15:01 and 16:00         |   4  |
|  Between 16:01 and 17:00         |   3  |
|  Between 17:01 and 18:00         |   2  |
|  > 18:01 and 19:00               |   1  |


*Total Presentation Time Points: *

## Subjective Components (For After Presentation):

Please rate the following components 1-3, with 1 being the lowest, and 3 being the highest. If necessary, you can use the first presenters as a baseline with a score of 2. 

* Were you convinced by the presentation? [     /3]
* Was the presentation lively? [      /3]
* Did the presentation flow logically?  [     /3]
* Did the presentation feel polished/complete? [      /3]
* Was the analysis of the presentation at a sufficient level for having completed 140A? [      /3]
* Were the statistics relevant to the project and provide good insights? [      /3]
* Did the figures add to the presentation? [      /3]
* Does it seem like these students know how to use R competently? [      /3] 


*Total Subjective Components Points: *




**TOTAL POINTS OVERALL (44 POSSIBLE):**



