---
title: "Rubrik Competition"
author: "Data Hack 2022"
date: "`r format(Sys.time(), '%A %D')`" 
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

On Friday, June 02, 2022, the enrolled students of the class 199RA (Data Hack), divided into 6 groups, will present their work in the context of a "Competition". The main goal of the presentation is to convince the judges about a topic that California policy makers need to address/change/solve. 
Each group would have up to 15 minutes to present. They will be judged across multiple dimensions. Each dimension has an associated score, ranging from 1 to 5, 5 being the best score possible. The judges would be the ones in charge of the score, therefore the students would need to convince them about their topics. 
The Instructors will check the time and inform each group when there are 5 minutes left, 1 minute left and when the time is done. 
Next, we outline and describe how the scores for each dimension will be calculated for all groups:

# Dimensions

## Time


| Presentation time (min:sec)      |  Score   |
|----------------------------------|----------|
|  < 15:01                         |   5  |
|  Between 15:01 and 16:00         |   4  |
|  Between 16:01 and 17:00         |   3  |
|  Between 17:01 and 18:00         |   2  |
|  > 18:01 and 19:00               |   1  |



## Graphs clarity

For each graph that fails to clarify the name of the axis, the scale of them, we will deduct....


## Motivation 



## Data Wrangling Process

Need to explain the data wrangling process. Where did they got the data from, did they merge it, what sort of drawbacks they faced, etc..

## Evidence

Need to show convincingly, why the topic is important. 

## 


# Students


# Judges


# Instructors








