---
title: "Topic Proposal Assignment"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

For this assignment, you will need to coordinate with your respective groups. Recall from the syllabus that this year's Data Hack competition is focused on California policy. In particular, it is your group's responsibility to convince a panel of judges that your topic is what should be prioritized by California policy makers. For instance, some topics that you may believe are critically important in California right now:

* Wildfires
* Drought
* Crime 
* Rental Prices
* Gas Prices
* Air Pollution
* Gang Membership
* Immigration 
* Social Media Addiction

Notice that many of these examples are not *specific* to California, but they are all problems that California experiences. 

# Assignment

Decide among your group members which topic you would like to do. You need to turn in a brief proposal on Friday, April 22 which will be made available on Gauchospace. Here are the criteria for the proposal:

* Specify the topic of interest and explain why that topic is important to policy makers. This doesn't have to be in-depth, but it should give some context to the problem. Think of this a writing how you would begin your presentation (e.g., the motivation).
* Specify a list of data sources that you believe you can use, and the pathways to getting these data sources. Furthermore, here are some questions you should address: Is the data readily available? Can you download the data immediately? Will you need to webscrape the data? Is the data in PDF format? Will you need to merge the data with another source? Who maintains the data? Is this a reliable source of data? Are there enough columns/rows do to substantial analysis?
* Specify some ideas for analysis or graphs that you may be able to show using the data. Your group may not have the skills necessary for these graphs or analysis yet, but thinking of some ideas will help you determine if your data is appropriate.
* Write out each of the group members in your group in a separate section. 

In sum, this proposal should be around 1-1.5 pages single-spaced. Of course, there is no page quota, and as long as you answer the above questions, you will get full credit. However, please be sure that your proposal is organized in a manner that makes it easy for a reader to understand.

